.TH farfetched 1 "" ""  "Fetches across great distances"

.SH NAME
.\" #####

\fBfarfetched\fR - fetches git repositories recursively in other directories

.SH SYNOPSIS

\fBfarfetched\fR [directory]

.SH DESCRIPTION

\fBfarfetched\fR fetches all the gitrepositories within a given directory recursively.
If no directory is given, the current working directory is used instead.

.SH OPTIONS

\fBdirectory\fR - the directory to fetch in, defaults to \fB.\fR

.SH AUTHOR

\fBDarkWiiPlayer\fR <darkwiiplayer@hotmail.com>

.SH SEE ALSO

\fBgit(1)\fR,
\fBgit-fetch(1)\fR,
\fBfind(1)\fR
