.TH mansplain 1 "" ""  "Explains things like you don't know"

.SH NAME
.\" #####

\fBmansplain\fR - shows a selected manpage in zathura

.SH SYNOPSIS

\fBmansplain\fR

.SH DESCRIPTION

\fBmansplain\fR presents the user a menu to select a manpage.
It then shows the selected manpage in a PDF viewer in a separate window.

.SH OPTIONS

\fBnone\fR - mansplain accepts no options as of yet

.SH TODO

mansplain should accept an optional argument to select a manpage directly without showing any menu.

.SH AUTHOR

\fBDarkWiiPlayer\fR <darkwiiplayer@hotmail.com>

.SH SEE ALSO

\fBman(1)\fR,
\fBdmenu(1)\fR,
\fBzathura(1)\fR
